/* Generated by Babel */
"use strict";

var food = function food(foodname, type) {
    if (foodname !== "burrito" || type !== "breakfast") {
        console.log("Sorry No Food for you!");
    }
};

food("burito", "lunch");